### ISSUE TITLE
Resources files not found in Release mode

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#27]
I find running with Debug mode works fine but for Release the resource files can't be found: 
![screenshot-release](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/76d4b42c-3e1f-49fd-b116-a2b9863c84b4)

This file does exist at ~/Dos/Civ1/

In case relevant this is with MonoDevelop on Linux.

**Comment by richardpenman** [comment]
The reason is `this.oCPU.DefaultDirectory` is an empty string in Release but defined correctly in Debug.

**Comment by rajko-horvat** [comment]
No, it should be that way, because in release mode, as per instructions in Readme.txt the OpenCiv1.exe is intended to be put directly into directory where all resource are (This is done for simplicity, for example the directory can be: 'c:\Dos\Civ1\', or '~/Dos/Civ1/' or anything you like).

Like this:

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/13e4810e-872c-44e8-97a1-6acd162b67ab)

**Comment by richardpenman** [comment]
ah OK, thanks. Was about to submit a PR to remove that! https://github.com/rajko-horvat/OpenCiv1/blob/master/CPU/CPU.cs#L83
