### ISSUE TITLE
Map doesn't properly display enemy moves near my units/cities

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#31]
I'm not following enemy moves, even though it's enabled in game options.

**Comment by rajko-horvat** [comment]
I'm guessing you mean that map doesn't properly display enemy moves near your units and cities.
Please keep in mind that most units (and cities) see only one square ahead (in every direction). When I toggle debug mode, map displays enemy city of size 4, and when I toggle it off, I see the city of size 2 because the distance from the nearest unit is 2 squares.
Also, please check with old CIV.EXE if this bug is present of not.

**Comment by axx0** [comment]
Can confirm this bug. A barbarian party attacked my city and I didn't see it. Only a dialog appeared notifying me that my city's population decreased after the attack.

**Comment by rajko-horvat** [comment]
Thanks for verifying. The soon I transfer more code to managed the sooner we can tackle this issues... :)

**Comment by rajko-horvat** [comment]
I just realized if the map is in focus you can see the enemy moves, but if it's outside focus then enemy moves are not shown. I guess it's something with signed/unsigned conversion as I found a lot of these in the code. Please be patient ;)

**Comment by rajko-horvat** [comment]
Should work correctly as of last commit.

**Comment by axx0** [comment]
Can confirm it works.
