### ISSUE TITLE
Crash when discovering a new technology

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#46]
**To Reproduce**
Load this save:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14805068/CIVIL0.zip)
End the turn.
Right after discovering Electronics, the game crashes

**Comment by rajko-horvat** [comment]
Thank you for testing ;) I have patched another Index out of range. The original source is full of them, but, because this is managed environment such events are checked, old CIV would just read or write at a random location in data memory segment, that's why old CIV works (sometimes corrupting the memory data at that position!)

**Comment by hadabascus** [comment]
No problem, thanks for making this!
Confirmed that the new patch fixes this.
