### ISSUE TITLE
Unable to harvest a city square

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#49]
**Describe the bug**
Unable to select the Fish square in the city to get 2 Food and 3 Trade.

**To Reproduce**
1. Load the save:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14899879/CIVIL0.zip)
2. Go to city screen of city named Izibia 
3. Mouse-click on fish

**Comment by rajko-horvat** [comment]
If you run sometimes into this sort of problems, enable/disable the debug mode (Alt+D) which shows entire map.
The problem is that the enemy unit is in the square you are trying to select:
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/b100ac86-8f95-4196-bd4d-101c47e34d17)

Or if I simply go near that square with Chariot I can see an enemy Sail
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/bb5dd7b0-910d-4171-9bd1-986e2ec3c288)
 
Unfortunately you don't have a line of sight to see this unit :)
It would be a logical thing to mark it with a red rectangle or something, but then you would know that somebody is on that square... This problem needs some more thinking ;)

**Comment by hadabascus** [comment]
You are of course correct. Not a bug, happens in original game also.
