### ISSUE TITLE
Crash due to trireme loss in sea waters

### ISSUE THREAD

**Issue by hsedd** [rajko-horvat/OpenCiv1#52]
Crash due to trireme loss in sea waters

**Comment by rajko-horvat** [comment]
Did you use pre-built Alpha-v7, or did you built from code, latest Branch ('Transfer-unmanaged-data-to-managed-and-code-cleanup')?

**Comment by hsedd** [comment]
Latest branch :) thank you for the quick reply!

**Comment by rajko-horvat** [comment]
Ok, could you please provide save game before crash happened (.sve, .map)?
It's the easiest and quickest way to see what happened and fix the problem :)

**Comment by rajko-horvat** [comment]
> Latest branch :) thank you for the quick reply!

'Master' or 'Transfer-unmanaged-data-to-managed-and-code-cleanup' Branch?

The latest is the 'Transfer-unmanaged-data-to-managed-and-code-cleanup'.

**Comment by hsedd** [comment]
Thank you! I just checked out the current master branch and ran it on macos. Savegame is attached. Simply take the trireme from Byzantium. In the same game, it happened also before, without Magellans Voyage.
[Archiv.zip](https://github.com/user-attachments/files/15875019/Archiv.zip)

**Comment by rajko-horvat** [comment]
The original code has a bunch of Index out of range errors (A bunch has been already patched).
They never got caught before because there was no array indexing error checking mechanism at all in the old C compiler (that Sid used, hence all the corruption bugs in the game that people mention).

The current errors have been patched, but I will need to recheck it later.

Trireme that's lost on sea now no longer produces Index out or Range error, and there was also an index out of range error (also patched) with an unit in the city in the sample that you provided.

Happy playing ;)

**Comment by rajko-horvat** [comment]
I'm going to close this as this bug is fixed. Feel free to reopen it if needed.

**Comment by rajko-horvat** [comment]
I'm going to close this as this bug is fixed. Feel free to reopen it if needed.

**Comment by hsedd** [comment]
Thank you a lot for your quick reaction and even a fix! Thank you for your engagement, it is really cool to play civ in a modern operating system!

**Comment by rajko-horvat** [comment]
> Thank you a lot for your quick reaction and even a fix! Thank you for your engagement, it is really cool to play civ in a modern operating system!

Thank you for testing an Alpha release. Special thanks to you that are testing this new release ;)
