### ISSUE TITLE
When starting a new game, the background of the intro text becomes opaque

### ISSUE THREAD

**Issue by 1oom-fork** [rajko-horvat/OpenCiv1#55]
**Expected behavior**
The background of the text should be transparent and not spoil the background

![Screenshot_20240624_132931](https://github.com/rajko-horvat/OpenCiv1/assets/23404794/d4557b67-7a66-48ab-a9c6-d4deb941e626)

**Desktop:**
Arch Linux / Plasma

**Comment by rajko-horvat** [comment]
That is the expected behavior, the original also displays this, as it's due to map generation on Screen 2.

**Comment by 1oom-fork** [comment]
I don't think so
![image](https://github.com/rajko-horvat/OpenCiv1/assets/23404794/29f683a9-970d-471d-bd83-089cf38806d1)

**Comment by rajko-horvat** [comment]
> I don't think so !

Be warned!
I find such language is inappropriate, disrespectful and is not constructive in any way. If you insist and continue with such I will be forced to take actions. For any further information on what is acceptable conduct please take a look at our [Code of Conduct](https://github.com/rajko-horvat/OpenCiv1?tab=coc-ov-file)

And now a clarified reply to your question:
I have verified this bug is present in the original version also, and I find no reason to explain myself any further.
